name: nlp_ml_sentiment_analysis
channels:
  - https://repo.anaconda.com/pkgs/snowflake
dependencies:
  - python=3.8
  - cachetools=4.2.2
  - jupyter
  - numpy=1.23.1
  - joblib=1.1.1
  - pandas=1.4.4
  - scikit-learn=1.2.0
  - nltk=3.7
  - snowflake-snowpark-python=0.11.0
  - pip=22.3.1
  - isort=5.9.3
  - black=22.6.0
  - pip:
    - jupyter
    - streamlit